### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by DemonAlbert** [microsoft/BioGPT#10]
Hi  when i run the code 
![image](https://user-images.githubusercontent.com/50090212/200722183-118acebb-d113-49a3-834e-73250f36e45c.png)
 raised an error  ![image](https://user-images.githubusercontent.com/50090212/200721629-9fd9995d-f1c9-44f2-8fd0-7ac5b1010617.png)  I don't know how to address such error .would you please give a hand?

**Comment by renqianluo** [comment]
Please refer to our updated dependencies in [README.md](https://github.com/microsoft/BioGPT/blob/main/README.md)
