### ISSUE TITLE
raise ProcessExitedException

### ISSUE THREAD

**Issue by DemonAlbert** [microsoft/BioGPT#11]
hello, I followed the instructions in GitHub https://github.com/microsoft/BioGPT/tree/main/examples/RE-DDI  but raised an error 
 i also dont konw how to solve such quesiton . would you please give me a hand?
![image](https://user-images.githubusercontent.com/50090212/200723162-2a308069-a153-4309-9749-20ef2f75b194.png)

**Comment by renqianluo** [comment]
You can try train it on single card and see whether error occurs. BTW, there might be some error due to dependencies updated. Please refer to the updated [README.md](https://github.com/microsoft/BioGPT/blob/main/README.md) now.
