### ISSUE TITLE
Not able to import fairseq

### ISSUE THREAD

**Issue by Arjun-Ramesh-tech** [microsoft/BioGPT#12]
Followed the requirements and installation step and downloaded the pretrained model on google colab using the readme.md file (https://github.com/microsoft/BioGPT).

If i try to import fairseq, i get the error
<img width="877" alt="Screenshot 2022-11-17 at 5 30 48 PM" src="https://user-images.githubusercontent.com/69165736/202589670-151c7cd7-26f4-465d-9911-f4e1bb5e892b.png">

Not sure if i'm missing something here. Appreciate any help.

**Comment by renqianluo** [comment]
Please check and follow the updated README.md now
