### ISSUE TITLE
Please post pre-print of the manuscript

### ISSUE THREAD

**Issue by matthias-samwald** [microsoft/BioGPT#2]
I cannot access the Briefings in Bioinformatics paper through my institution, and many other interested readers will have the same problem. Please consider posting a pre-print of the manuscript (e.g. in arXiv). Thanks!

**Comment by renqianluo** [comment]
Hi, @matthias-samwald , you can access the paper via this [link](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbac409/6713511?guestAccessKey=a66d9b5d-4f83-4017-bb52-405815c907b9)
