### ISSUE TITLE
Only the first checkpoint link works

### ISSUE THREAD

**Issue by evolu8** [microsoft/BioGPT#20]
Are the links for pretrained models beyond the first intentionally dead? 

Would love access to the Large Q&A version. Is there an ETA if 'coming soon'?

Best

**Comment by Jordigg2000** [comment]
Hi! you can access the files by adding .tgz to the urls, for example "https://msramllasc.blob.core.windows.net/modelrelease/BioGPT/checkpoints/QA-PubMedQA-BioGPT-Large.tgz"

it seems that they have forgotten to add the extensions at all checkpoints.
