### ISSUE TITLE
checkpoint downloads often break

### ISSUE THREAD

**Issue by ZiyeLuo** [microsoft/BioGPT#3]
Congratulations on your work. Can you please package several sub-packages in checkpoints separately and provide download links for them? I wanted to experiment with your checkpoint but I found that the download often broke when I used wget to download it

**Comment by minstar** [comment]
I also got this problem when I try to download the provided pre-train model's checkpoint

**Comment by renqianluo** [comment]
Hi @ZiyeLuo and @minstar , this may be due to the large file size. I have splitted them into smaller pieces. Please check the updated README.md.

@ZiyeLuo , @minstar also got around this. You can try it.
