### ISSUE TITLE
Cannot run interactive.py in text_generation dir.

### ISSUE THREAD

**Issue by knagamatsu** [microsoft/BioGPT#32]
I ran interactive.py file in text_generation dir and got the following error.
`FileNotFoundError: [Errno 2] No such file or directory: '/home/********/BioGPT/data/PubMed/data-bin/dict.txt'`
There certainly does not appear to be a corresponding directory.

Instead, changing the directory referenced in interactive.py as shown below seems to have executed without problems.
`parser.add_argument("--data_dir", type=str, default="../../data/PubMedQA/raw") #try to fix`

Could you please check this error?

**Comment by knagamatsu** [comment]
Sorry. I understood the usage.

**Comment by malber** [comment]
in the latest release [e49e580](https://github.com/microsoft/BioGPT/commit/e49e5809bd317c4a1b6cb8498659e27d4e70814a), the above solution works pointing to the root data without the PubMedQA part.

**Comment by rezabuughunter** [comment]
Ok:)
