### ISSUE TITLE
Unable to find the PubMed/data-bin file

### ISSUE THREAD

**Issue by minstar** [microsoft/BioGPT#4]
Hi,

I am trying to use BioGPT for generating some biomedical text.
However, PubMed/data-bin file needs to load the pre-trained checkpoint of the biogpt model.
I could not find a way to download this file.
Let me know if I can get this.

Thanks

**Comment by renqianluo** [comment]
Hi, the PubMed/data-bin is a folder actually containing the vocabulary file. I have updated the README.md, please check it.
https://github.com/microsoft/BioGPT#example-usage
