### ISSUE TITLE
Unable to download the checkpoints

### ISSUE THREAD

**Issue by zequnl** [microsoft/BioGPT#7]
Hi,
I tried to download the checkpoints with `wget https://msralaphilly2.blob.core.windows.net/ml-la/release/BioGPT/checkpoints.tgz` but got `ERROR 404: The specified resource does not exist..`. So I wonder whether there is some problem about the download link. I would be grateful if you could check it. THX！

**Comment by renqianluo** [comment]
Previous link is broken. Have updated the new link. Please refer to the updated README at https://github.com/microsoft/BioGPT/commit/090440c3945a06e6f0c1861b7487cde129b95a78
