### ISSUE TITLE
load and finetune

### ISSUE THREAD

**Issue by ZiyeLuo** [microsoft/BioGPT#9]
Hi, I am finding it difficult to use fairseq framework. Do you know how to import models directly with pytorch and fine-tune them?

**Comment by renqianluo** [comment]
@ZiyeLuo  We will try to convert it.

**Comment by kamalkraj** [comment]
Hi,
I am working on a PR to implement BioGPT with huggingface transformers - https://github.com/huggingface/transformers/pull/20420

progress so far
![Screenshot 2022-11-23 at 11 56 07 PM](https://user-images.githubusercontent.com/17096858/203621495-3f10c595-4be4-4ac6-abef-33dae21daff4.png)

Install transformers from this PR for experiments.

**Comment by renqianluo** [comment]
@kamalkraj  That is very cool!

**Comment by parthplc** [comment]
Hey @kamalkraj, I used the Text Generation model but not the question-answering model in the above manner. Any suggestion on how I can use it?
