### ISSUE TITLE
Question Answering on PubMedQA in Reasoning Required Setting

### ISSUE THREAD

**Issue by ZON-ZONG-MIN** [microsoft/BioGPT#91]
[BioGPT](https://github.com/microsoft/BioGPT)/[examples](https://github.com/microsoft/BioGPT/tree/main/examples)/[QA-PubMedQA](https://github.com/microsoft/BioGPT/tree/main/examples/QA-PubMedQA)/README.md

In this README.md, I need to Copy the files `pqal_fold0/train_set.json`, `pqal_fold0/dev_set.json`, `test_set.json` and `test_ground_truth.json` to `../../data/PubMedQA/raw`

but I can't found the files `pqal_fold0/train_set.json`, `pqal_fold0/dev_set.json`, `test_set.json` in [PubMedQA](https://github.com/pubmedqa/pubmedqa)

I only found `test_ground_truth.json`

How should I do it?:smiley:
Thanks

**Comment by rezabuughunter** [comment]
not bad

**Comment by rezabuughunter** [comment]
not bad
